title = "wigum::website"
base_url = "https://willguimont.com/"
description = "William Guimont-Martin's personal website"

compile_sass = true
minify_html = true
generate_feeds = true
# Only the first file will be used in the navbar feed button,
# other feeds will still be available in page's head.
feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true
author = "William Guimont-Martin"

theme = "duckquill"

# Based on https://github.com/welpo/tabi
#
# To translate the entire theme, there must be a file with the same ISO 639-1 or BCP 47
# language code in the `i18n` directory of your site or the Duckquill theme.
# For example, "i18n/fr.toml" for French or "i18n/zh-Hans.toml" for Simplified Chinese.
# Otherwise the theme will be in English.
#
# ISO 639-1: https://localizely.com/iso-639-1-list/
# BCP 47: https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
default_language = "en"

taxonomies = [{ name = "tags", feed = true }]

[markdown]

smart_punctuation = true
bottom_footnotes = true

[markdown.highlighting]
style = "class"
light_theme = "solarized-light"
dark_theme = "solarized-dark"

[search]
index_format = "fuse_json"

[extra]
# Which theme should be used by default (light/dark).
#
default_theme = "dark"
#
# Sets theme and browser theme color.
# See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
accent_color = "#0066ff"
# Ditto but for the dark theme.
# If not set regular variant will be used.
accent_color_dark = "#66ccff"
# Whether to use fonts bundled with Duckquill instead of system ones.
# Keep in mind that it also changes the style of headings.
#
# bundled_fonts = true
#
# Use emoji as a favicon.
# Only one emoji is being rendered, everything else is truncated.
#
# emoji_favicon = "ðŸ¦†ðŸª¶"
#
# URL to website's issue tracker
issues_url = "https://github.com/willGuimont/willGuimont.github.io/issues"
# URL to website's source code
source_url = "https://github.com/willGuimont/willGuimont.github.io"
# Additional CSS styles; expects them to be in the "./static/" directory.
# If you are using Sass it will be generated there automatically.
#
styles = [
	"custom.css"
]
#
# Additional JavaScript scripts; expects them to be in the "./static/" directory.
#
# scripts = [
#   "YOUR_SCRIPT.js",
#   "ALSO_YOUR_SCRIPT.js"
# ]
#
# Whether to show "copy code" button on all code blocks
# that have the language set.
# See https://www.getzola.org/documentation/content/syntax-highlighting/
show_copy_button = true
# Whether to show estimated read time in posts.
show_reading_time = true
#
# Whether to show a share button in article's quick actions.
# Uses https://shareopenly.org.
show_share_button = true
# Whether to show the backlinks button for linked articles in the article's quick actions
show_backlinks = true
# Whether to enable the KaTeX library for rendering LaTeX.
# Note: This will make your page significantly heavier.
# Instead, consider enabling it per page/section.
# katex = true
#
# Whether to render table of contents on all pages.
# Will not be rendered if page doesn't have any headings.
# Can be set per page/section.
toc = true

# Whether to render inline table of contents at the top of all pages,
# in addition to floating quick navigation buttons.
# Can be set per page/section.
toc_inline = true

# Whether to use numbered (ordered) list for table of contents.
# Can be set per page/section.
toc_ordered = true
toc_sidebar = true

# Custom separator used across the theme.
# separator = "â€¢"
# Custom separator used in title tag and posts metadata.
# title_separator = "-"
#
# Whether to use Content Security Policy.
# Keep in mind that although this can potentially increase security,
# it can break some stuff, in which case you will need to set custom policy.
csp = [
	{ directive = "font-src", domains = [
		"'self'",
	] },
	{ directive = "img-src", domains = [
		"'self'",
		"https:",
		"data:",
	] },
	{ directive = "media-src", domains = [
		"'self'",
		"https:",
	] },
	{ directive = "script-src", domains = [
		"'self'",
	] },
	{ directive = "style-src", domains = [
		"'self'",
		"'unsafe-inline'",
	] },
	{ directive = "frame-src", domains = [
		"https://player.vimeo.com",
		"https://www.youtube-nocookie.com",
		"https://toot.community",
	] },
	{ directive = "connect-src", domains = [
		"https://toot.community",
	] },
	{ directive = "base-uri", domains = [
		"'none'",
	] },
	{ directive = "form-action", domains = [
		"'none'",
	] },
]
# Uncomment this to disable the card displayed in share previews
card = false

[extra.nav]
# Whether to automatically hide nav when not hovered or focused
# auto_hide = true
# Whether to show the Atom/RSS feed button in the nav
show_feed = true
# Whether to show the manual theme switcher in the nav
show_theme_switcher = true
# Whether to show the link to the source repository in the nav
show_repo = true
# Links used in the nav.
# For local files use same link format as in Markdown,
# i.e. "@/blog/_index.md".
# See https://www.getzola.org/documentation/content/linking/#internal-links
links = [
	# { url = "@/demo/index.md", name = "Demo" },
	{ url = "@/blog/_index.md", name = "Blog" },
	{ name = "Links", menu = [
		{ url = "https://github.com/willGuimont", name = "GitHub" },
		{ url = "https://www.youtube.com/@willGuimont", name = "YouTube" },
		{ url = "https://www.linkedin.com/in/william-guimont-martin/", name = "LinkedIn" },
		{ url = "https://www.thingiverse.com/wigum/designs", name = "Thingiverse" },
		{ url = "https://cults3d.com/en/users/wigum/", name = "Cults3D" },
		{ url = "https://www.instagram.com/wilguimont/", name = "Instagram" },
		{ url = "https://scholar.google.com/citations?user=sZIyj3IAAAAJ&hl=en", name = "Google Scholar" },
		{ url = "https://www.researchgate.net/profile/William-Guimont-Martin", name = "ResearchGate" },
		{ url = "https://mastodon.social/@willGuimont", name = "Mastodon" },
		{ url = "https://ko-fi.com/wigum", name = "Coffee" },
	] },
]

[extra.footer]
# Links used in the footer.
# Same as the nav ones.
# links = [
# 	{ url = "@/blog/_index.md", name = "Blog" },
# 	{ url = "@/demo/index.md", name = "Demo" },
# 	{ name = "Links", menu = [
# 		{ url = "https://github.com/willGuimont", name = "GitHub" },
# 	] },
# ]
# Social links in the footer.
# Any URL-encoded SVG can be used as an icon.
# https://simpleicons.org is the recommended source of SVG icons.
# For URL encoding use https://yoksel.github.io/url-encoder/.
# Make sure that "external quotes" are set to "double".
socials = [
	{ url = "https://github.com/willGuimont", name = "GitHub", icon = "%3Csvg%20role%3D%27img%27%20viewBox%3D%270%200%2024%2024%27%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%3E%3Ctitle%3EGitHub%3C%2Ftitle%3E%3Cpath%20d%3D%27M12%20.297c-6.63%200-12%205.373-12%2012%200%205.303%203.438%209.8%208.205%2011.385.6.113.82-.258.82-.577%200-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422%2018.07%203.633%2017.7%203.633%2017.7c-1.087-.744.084-.729.084-.729%201.205.084%201.838%201.236%201.838%201.236%201.07%201.835%202.809%201.305%203.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93%200-1.31.465-2.38%201.235-3.22-.135-.303-.54-1.523.105-3.176%200%200%201.005-.322%203.3%201.23.96-.267%201.98-.399%203-.405%201.02.006%202.04.138%203%20.405%202.28-1.552%203.285-1.23%203.285-1.23.645%201.653.24%202.873.12%203.176.765.84%201.23%201.91%201.23%203.22%200%204.61-2.805%205.625-5.475%205.92.42.36.81%201.096.81%202.22%200%201.606-.015%202.896-.015%203.286%200%20.315.21.69.825.57C20.565%2022.092%2024%2017.592%2024%2012.297c0-6.627-5.373-12-12-12%27%2F%3E%3C%2Fsvg%3E" },
	{ url = "https://bsky.app/profile/willguimont.bsky.social", name = "Bluesky", icon = "%3Csvg%20role%3D%27img%27%20viewBox%3D%270%200%20600%20530%27%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%3E%3Cpath%20d%3D%27m135.72%2044.03c66.496%2049.921%20138.02%20151.14%20164.28%20205.46%2026.262-54.316%2097.782-155.54%20164.28-205.46%2047.98-36.021%20125.72-63.892%20125.72%2024.795%200%2017.712-10.155%20148.79-16.111%20170.07-20.703%2073.984-96.144%2092.854-163.25%2081.433%20117.3%2019.964%20147.14%2086.092%2082.697%20152.22-122.39%20125.59-175.91-31.511-189.63-71.766-2.514-7.3797-3.6904-10.832-3.7077-7.8964-0.0174-2.9357-1.1937%200.51669-3.7077%207.8964-13.714%2040.255-67.233%20197.36-189.63%2071.766-64.444-66.128-34.605-132.26%2082.697-152.22-67.108%2011.421-142.55-7.4491-163.25-81.433-5.9562-21.282-16.111-152.36-16.111-170.07%200-88.687%2077.742-60.816%20125.72-24.795z%27%20fill%3D%27%231185fe%27%2F%3E%3C%2Fsvg%3E" },
	{ url = "https://instagram.com/wilguimont", name = "Instagram", icon = "%3Csvg%20role%3D%27img%27%20viewBox%3D%270%200%2024%2024%27%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%3E%3Ctitle%3EInstagram%3C%2Ftitle%3E%3Cpath%20d%3D%27M7.0301.084c-1.2768.0602-2.1487.264-2.911.5634-.7888.3075-1.4575.72-2.1228%201.3877-.6652.6677-1.075%201.3368-1.3802%202.127-.2954.7638-.4956%201.6365-.552%202.914-.0564%201.2775-.0689%201.6882-.0626%204.947.0062%203.2586.0206%203.6671.0825%204.9473.061%201.2765.264%202.1482.5635%202.9107.308.7889.72%201.4573%201.388%202.1228.6679.6655%201.3365%201.0743%202.1285%201.38.7632.295%201.6361.4961%202.9134.552%201.2773.056%201.6884.069%204.9462.0627%203.2578-.0062%203.668-.0207%204.9478-.0814%201.28-.0607%202.147-.2652%202.9098-.5633.7889-.3086%201.4578-.72%202.1228-1.3881.665-.6682%201.0745-1.3378%201.3795-2.1284.2957-.7632.4966-1.636.552-2.9124.056-1.2809.0692-1.6898.063-4.948-.0063-3.2583-.021-3.6668-.0817-4.9465-.0607-1.2797-.264-2.1487-.5633-2.9117-.3084-.7889-.72-1.4568-1.3876-2.1228C21.2982%201.33%2020.628.9208%2019.8378.6165%2019.074.321%2018.2017.1197%2016.9244.0645%2015.6471.0093%2015.236-.005%2011.977.0014%208.718.0076%208.31.0215%207.0301.0839m.1402%2021.6932c-1.17-.0509-1.8053-.2453-2.2287-.408-.5606-.216-.96-.4771-1.3819-.895-.422-.4178-.6811-.8186-.9-1.378-.1644-.4234-.3624-1.058-.4171-2.228-.0595-1.2645-.072-1.6442-.079-4.848-.007-3.2037.0053-3.583.0607-4.848.05-1.169.2456-1.805.408-2.2282.216-.5613.4762-.96.895-1.3816.4188-.4217.8184-.6814%201.3783-.9003.423-.1651%201.0575-.3614%202.227-.4171%201.2655-.06%201.6447-.072%204.848-.079%203.2033-.007%203.5835.005%204.8495.0608%201.169.0508%201.8053.2445%202.228.408.5608.216.96.4754%201.3816.895.4217.4194.6816.8176.9005%201.3787.1653.4217.3617%201.056.4169%202.2263.0602%201.2655.0739%201.645.0796%204.848.0058%203.203-.0055%203.5834-.061%204.848-.051%201.17-.245%201.8055-.408%202.2294-.216.5604-.4763.96-.8954%201.3814-.419.4215-.8181.6811-1.3783.9-.4224.1649-1.0577.3617-2.2262.4174-1.2656.0595-1.6448.072-4.8493.079-3.2045.007-3.5825-.006-4.848-.0608M16.953%205.5864A1.44%201.44%200%201%200%2018.39%204.144a1.44%201.44%200%200%200-1.437%201.4424M5.8385%2012.012c.0067%203.4032%202.7706%206.1557%206.173%206.1493%203.4026-.0065%206.157-2.7701%206.1506-6.1733-.0065-3.4032-2.771-6.1565-6.174-6.1498-3.403.0067-6.156%202.771-6.1496%206.1738M8%2012.0077a4%204%200%201%201%204.008%203.9921A3.9996%203.9996%200%200%201%208%2012.0077%27%2F%3E%3C%2Fsvg%3E" },
	{ url = "https://scholar.google.com/citations?user=sZIyj3IAAAAJ&hl=en", name = "Google Scholar", icon = "%3Csvg%20role%3D%27img%27%20viewBox%3D%270%200%2024%2024%27%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%3E%3Ctitle%3EGoogle%20Scholar%3C%2Ftitle%3E%3Cpath%20d%3D%27M5.242%2013.769L0%209.5%2012%200l12%209.5-5.242%204.269C17.548%2011.249%2014.978%209.5%2012%209.5c-2.977%200-5.548%201.748-6.758%204.269zM12%2010a7%207%200%201%200%200%2014%207%207%200%200%200%200-14z%27%2F%3E%3C%2Fsvg%3E" },
	{ url = "https://x.com/WilliamGuimont", name = "Twitter", icon = "%3Csvg%20role%3D%27img%27%20width%3D%27300%27%20height%3D%27300.251%27%20version%3D%271.1%27%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%3E%3Cpath%20d%3D%27M178.57%20127.15%20290.27%200h-26.46l-97.03%20110.38L89.34%200H0l117.13%20166.93L0%20300.25h26.46l102.4-116.59%2081.8%20116.59h89.34M36.01%2019.54H76.66l187.13%20262.13h-40.66%27%2F%3E%3C%2Fsvg%3E" },
	{ url = "https://mastodon.social/@willGuimont", name = "Mastodon", icon = "%3Csvg%20role%3D%27img%27%20viewBox%3D%270%200%2024%2024%27%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%3E%3Ctitle%3EMastodon%3C%2Ftitle%3E%3Cpath%20d%3D%27M23.268%205.313c-.35-2.578-2.617-4.61-5.304-5.004C17.51.242%2015.792%200%2011.813%200h-.03c-3.98%200-4.835.242-5.288.309C3.882.692%201.496%202.518.917%205.127.64%206.412.61%207.837.661%209.143c.074%201.874.088%203.745.26%205.611.118%201.24.325%202.47.62%203.68.55%202.237%202.777%204.098%204.96%204.857%202.336.792%204.849.923%207.256.38.265-.061.527-.132.786-.213.585-.184%201.27-.39%201.774-.753a.057.057%200%200%200%20.023-.043v-1.809a.052.052%200%200%200-.02-.041.053.053%200%200%200-.046-.01%2020.282%2020.282%200%200%201-4.709.545c-2.73%200-3.463-1.284-3.674-1.818a5.593%205.593%200%200%201-.319-1.433.053.053%200%200%201%20.066-.054c1.517.363%203.072.546%204.632.546.376%200%20.75%200%201.125-.01%201.57-.044%203.224-.124%204.768-.422.038-.008.077-.015.11-.024%202.435-.464%204.753-1.92%204.989-5.604.008-.145.03-1.52.03-1.67.002-.512.167-3.63-.024-5.545zm-3.748%209.195h-2.561V8.29c0-1.309-.55-1.976-1.67-1.976-1.23%200-1.846.79-1.846%202.35v3.403h-2.546V8.663c0-1.56-.617-2.35-1.848-2.35-1.112%200-1.668.668-1.67%201.977v6.218H4.822V8.102c0-1.31.337-2.35%201.011-3.12.696-.77%201.608-1.164%202.74-1.164%201.311%200%202.302.5%202.962%201.498l.638%201.06.638-1.06c.66-.999%201.65-1.498%202.96-1.498%201.13%200%202.043.395%202.74%201.164.675.77%201.012%201.81%201.012%203.12z%27%2F%3E%3C%2Fsvg%3E" },
]
# Whether to show "Â© Title, YEAR"
show_copyright = true
# Whether to show "Powered by Zola and Duckquill"
show_powered_by = false
# Whether to show link to website source
show_source = false
# Custom copyright text
#
# copyright = "Â© *Aperture* **Science** ~~Innovators~~, `1972`"

# Based on https://carlschwan.eu/2020/12/29/adding-comments-to-your-static-blog-with-mastodon/
#
# Mastodon-powered commenting.
# Values can be overridden in the front-matter, e.g.
# for multi-author blogs or guest posts.
#
# These variables are also used for Mastodon verification,
# the needed rel="me" link is set in the head based on these.
[extra.comments]
# Your Mastodon API host; instance that you have an account on.
host = "mastodon.social"
# Your Mastodon username; used to determine who the original poster is.
user = "willGuimont"
# Whether to show the QR code to Mastodon post
show_qr = true

# GoatCounter analytics; enabled only if present in config.
# [extra.goatcounter]
# Your GoatCounter server; goatcounter.com is used by default.
#
# host = "YOUR_SERVER"
#
# Your GoatCounter username
# user = "willGuimont"

[extra.debug]
# Display outlines around all elements for debugging purposes
layout = false
# Don't load any styles for debugging purposes
no_styles = false
